// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ0uB6kkV7laqu_VHExe7BcruiC7T4ESQ',
    appId: '1:121381794513:web:9735b1a435819d8d340bf0',
    messagingSenderId: '121381794513',
    projectId: 'auth-app-b5da8',
    authDomain: 'auth-app-b5da8.firebaseapp.com',
    storageBucket: 'auth-app-b5da8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyL20-qGvEgMD83QJsu8S4t1H89Wk8md0',
    appId: '1:121381794513:android:48fedf4d991b9e2c340bf0',
    messagingSenderId: '121381794513',
    projectId: 'auth-app-b5da8',
    storageBucket: 'auth-app-b5da8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC7B_EPpY4FJNWckNLG1euECjm7KAcXQA',
    appId: '1:121381794513:ios:7c1638a538f82cc7340bf0',
    messagingSenderId: '121381794513',
    projectId: 'auth-app-b5da8',
    storageBucket: 'auth-app-b5da8.firebasestorage.app',
    iosClientId: '121381794513-2r6n4ip205o22eovvku25tdf7n026ls8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC7B_EPpY4FJNWckNLG1euECjm7KAcXQA',
    appId: '1:121381794513:ios:7c1638a538f82cc7340bf0',
    messagingSenderId: '121381794513',
    projectId: 'auth-app-b5da8',
    storageBucket: 'auth-app-b5da8.firebasestorage.app',
    iosClientId: '121381794513-2r6n4ip205o22eovvku25tdf7n026ls8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ0uB6kkV7laqu_VHExe7BcruiC7T4ESQ',
    appId: '1:121381794513:web:c462624cb5257f25340bf0',
    messagingSenderId: '121381794513',
    projectId: 'auth-app-b5da8',
    authDomain: 'auth-app-b5da8.firebaseapp.com',
    storageBucket: 'auth-app-b5da8.firebasestorage.app',
  );
}
